spring.application.name=taskmanager
spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
jwt.secret=${JWT_SECRET:tF7uW2pQ9mZx4R8vL1cD5kG0sH3jN6bY}
jwt.expiration=${JWT_EXPIRATION:10800000}
spring.jpa.hibernate.ddl-auto=create-drop
