spring.application.name=taskmanager
spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT:5433}/taskmanager
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:10800000}
springdoc.swagger-ui.path=/docs
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=create-drop
